spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
        strategy: refresh
management:
  endpoint:
    restart:
      enabled: true

eureka:
  client:
    enabled: false
dekorate:
  kubernetes:
    serviceType: "NodePort"

kubernetes.trust.certificates: true