management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8070
  cloud:
    kubernetes:
      enabled: false
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true