spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
#    loadbalancer.ribbon.enabled: false

eureka:
  client:
    enabled: false

dekorate:
  kubernetes:
    serviceType: "NodePort"

# actuators shouldn't be public
management.endpoint.restart.enabled: true
