spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
eureka:
  client:
    enabled: false

dekorate:
  kubernetes:
    serviceType: "NodePort"

# actuators shouldn't be public
management.endpoint.restart.enabled: true