apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
{{ include "gateway.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: MANAGEMENT_SERVER_PORT
              value: "8000"
            - name:  SPRING_CLOUD_KUBERNETES_CONFIG_NAME
              value: {{ include "gateway.fullname" . }}-spring
            - name:  SPRING_CLOUD_KUBERNETES_SECRETS_NAME
              value: {{ include "gateway.fullname" . }}-spring
          ports:
            - name: http
              containerPort: 8070
              protocol: TCP
            - name: actuator
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: actuator
            initialDelaySeconds: 300
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: actuator
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
