{{- if .Values.rbac.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "gateway.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    helm.sh/chart: {{ include "gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "gateway.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    helm.sh/chart: {{ include "gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "gateway.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "gateway.fullname" . }}-config
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "gateway.fullname" . }}-sd
  labels:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    helm.sh/chart: {{ include "gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["services", "pods", "endpoints"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "gateway.fullname" . }}-sd
  labels:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    helm.sh/chart: {{ include "gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "gateway.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "gateway.fullname" . }}-sd
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}