apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fashion-bestseller.fullname" . }}-spring
  labels:
{{ include "fashion-bestseller.labels" . | indent 4 }}
data:
{{- if or (.Values.extraConfig) (.Values.extraSecret) }}
  application.yml: |-
    spring:
      cloud:
        kubernetes:
        {{- with .Values.extraConfig }}
          config:
            sources:
            {{ . | toYaml | indent 12 }}
        {{- end }}
        {{- with .Values.extraSecret }}
          secrets:
            sources:
            {{ . | toYaml | indent 12 }}
        {{- end }}
{{- end }}
{{- if .Values.config }}
{{ .Values.config | toYaml | indent 2 }}
{{- end }}