{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "toys-bestseller.serviceAccountName" . }}
  labels:
{{ include "toys-bestseller.labels" . | indent 4 }}
{{- end -}}
